### PR TITLE
fix cgroup2 support

### LINKED ISSUE #900: Support cgroups v2
`k3s-agent` is failing to run on Fedora 31. I suspect this is due to cgroups v2 being the default on Fedora 31, but can't quite figure out how to see which version of runc is shipping with k3s (runc recently landed support for cgroups v2)

**Version:**
`k3s version v0.9.1 (755bd1c6)`

**Describe the bug**
k3s-agent exits 1 and dies repeatedly with the following log output:
```
Oct 15 07:41:51 mercury systemd[1]: k3s-agent.service: Failed with result 'exit-code'.
Oct 15 07:41:51 mercury systemd[1]: k3s-agent.service: Main process exited, code=exited, status=1/FAILURE
Oct 15 07:41:51 mercury k3s[23212]: time="2019-10-15T07:41:51.403568863-07:00" level=fatal msg="failed to find memory cgroup, you may need to add \"cgroup_memory=1 cgroup_enable=memory\" to your linux cmdline (/boot/cmdline.txt on a Rasp>
Oct 15 07:41:51 mercury k3s[23212]: time="2019-10-15T07:41:51.403559607-07:00" level=error msg="Failed to find memory cgroup, you may need to add \"cgroup_memory=1 cgroup_enable=memory\" to your linux cmdline (/boot/cmdline.txt on a Rasp>
Oct 15 07:41:51 mercury k3s[23212]: time="2019-10-15T07:41:51.403539664-07:00" level=warning msg="Failed to find cpuset cgroup, you may need to add \"cgroup_enable=cpuset\" to your linux cmdline (/boot/cmdline.txt on a Raspberry Pi)"
Oct 15 07:41:51 mercury k3s[23212]: time="2019-10-15T07:41:51.403421758-07:00" level=info msg="Starting k3s agent v0.9.1 (755bd1c6)"
Oct 15 07:41:51 mercury systemd[1]: Started Lightweight Kubernetes.
Oct 15 07:41:51 mercury systemd[1]: Starting Lightweight Kubernetes...
Oct 15 07:41:51 mercury systemd[1]: Stopped Lightweight Kubernetes.
Oct 15 07:41:51 mercury systemd[1]: k3s-agent.service: Scheduled restart job, restart counter is at 1076.
Oct 15 07:41:51 mercury systemd[1]: k3s-agent.service: Service RestartSec=5s expired, scheduling restart.
.
.
.
```

**To Reproduce**
Start up a k3s agent on Fedora 31 Server

**Expected behavior**
Should start

**Actual behavior**
Doesn't and poops out the logs above

**Additional context**
Again, I think this is related to the cgroups v2 change, but couldn't figure out which version of runc is getting packaged with k3s right now to confirm. The most recent version of runc ([1.0.0-rc9](https://github.com/opencontainers/runc/releases/tag/v1.0.0-rc9)) is required for cgroups v2 to function.

### PR DESCRIPTION
**Pull request by AkihiroSuda**
#### Proposed Changes ####

cgroup2 support was introduced in #2584, but got broken in f3de60ff3191dc3a0ae7ce8393e388700f48ed88

It was failing with "F1210 19:13:37.305388    4955 server.go:181] cannot set feature gate SupportPodPidsLimit to false, feature is locked to true"

#### Types of Changes ####

BugFix

#### Verification ####

`sudo k3s server` on Ubuntu 20.10 with cgroup2

#### Linked Issues ####

Fix #900

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Opened https://github.com/k3s-io/k3s/issues/2845 for requesting cgroup v2 CI infra.

**Review by briandowns — APPROVED** [review]

**Review by brandond — APPROVED** [review]

**Comment by dweomer** [comment]
This looks fine to me but we really need @Oats87 to review.

File: pkg/daemons/agent/agent.go [hunk 1]
```diff
@@ -182,13 +184,34 @@ func checkCgroups() (kubeletRoot, runtimeRoot string, hasCFS, hasPIDs bool) {
 	}
 	defer f.Close()
 
+	v2 := cgroups.Mode() == cgroups.Unified
```
Comment (Oats87) [inline pkg/daemons/agent/agent.go:187]: I am not very familiar with `github.com/containerd/cgroups` behavior -- is it possible that we'll receive a `cgroups.Unified` result from `cgroups.Mode()` even if we don't have `systemd` as our init process?

i.e. on a system with unified cgroups but no systemd

File: pkg/daemons/agent/agent.go [hunk 2]
```diff
@@ -197,7 +220,7 @@ func checkCgroups() (kubeletRoot, runtimeRoot string, hasCFS, hasPIDs bool) {
 				if _, err := os.Stat(p); err == nil {
 					hasCFS = true
 				}
-			} else if system == "name=systemd" {
+			} else if system == "name=systemd" || v2 {
```
Comment (Oats87) [inline pkg/daemons/agent/agent.go:223]: When on a non-systemd system but with unified cgroups, is it OK that we aren't setting `kubeletRoot` if we don't have a `.scope`?

**Review by Oats87 — COMMENTED** [review]
Overall, this PR looks good to me, but I do have some concerns around functionality. As far as I can tell this will not break our existing `cgroupsv1` support, and so should be safe to merge, although we should do regression testing to verify this.

File: pkg/daemons/agent/agent.go (hunk 1 above)
Comment (AkihiroSuda) [reply pkg/daemons/agent/agent.go:187]: Yes,that is possible, as long as cgroup2 is mounted on /sys/fs/cgroup

File: pkg/daemons/agent/agent.go (hunk 2 above)
Comment (AkihiroSuda) [reply pkg/daemons/agent/agent.go:223]: I'm not familiar with kubeletRoot stuff honestly l, but this PR corresponds to the v1 behavior.

File: pkg/daemons/agent/agent.go (hunk 1 above)
Comment (brandond) [reply pkg/daemons/agent/agent.go:187]: @AkihiroSuda do you know if there is a non-systemd based system that only supports cgroups v2 that we could test this on?

Comment (AkihiroSuda) [reply pkg/daemons/agent/agent.go:187]: OpenRC seems to support cgroup v2 (aka "unified mode") as well:

https://github.com/OpenRC/openrc/blob/170ce2624a98952e6eb871cd9915c7c1b76ab887/etc/rc.conf#L194-L199

Comment (olljanat) [reply pkg/daemons/agent/agent.go:187]: @brandond FYI. I built version of k3OS which combines this PR with OpenRC on "unified" mode. You can find it from: https://github.com/olljanat/k3os/releases/tag/rootless-cgroup-v2-test

Afaiu cgroup is using v2 mode and k3s still works:
```
k3os-11941 [~]$ ls -l /sys/fs/cgroup/
total 0
drwxr-xr-x 2 root root 0 Jan 25 22:04 acpid
drwxr-xr-x 2 root root 0 Jan 25 22:04 ccapply
-r--r--r-- 1 root root 0 Jan 25 22:04 cgroup.controllers
-rw-r--r-- 1 root root 0 Jan 25 22:04 cgroup.max.depth
-rw-r--r-- 1 root root 0 Jan 25 22:04 cgroup.max.descendants
-rw-r--r-- 1 root root 0 Jan 25 22:04 cgroup.procs
-r--r--r-- 1 root root 0 Jan 25 22:04 cgroup.stat
-rw-r--r-- 1 root root 0 Jan 25 22:11 cgroup.subtree_control
-rw-r--r-- 1 root root 0 Jan 25 22:04 cgroup.threads
drwxr-xr-x 2 root root 0 Jan 25 22:04 connman
-rw-r--r-- 1 root root 0 Jan 25 22:04 cpu.pressure
-r--r--r-- 1 root root 0 Jan 25 22:04 cpuset.cpus.effective
-r--r--r-- 1 root root 0 Jan 25 22:04 cpuset.mems.effective
drwxr-xr-x 2 root root 0 Jan 25 22:04 dbus
drwxr-xr-x 2 root root 0 Jan 25 22:04 haveged
-rw-r--r-- 1 root root 0 Jan 25 22:04 io.cost.model
-rw-r--r-- 1 root root 0 Jan 25 22:04 io.cost.qos
-rw-r--r-- 1 root root 0 Jan 25 22:04 io.pressure
drwxr-xr-x 2 root root 0 Jan 25 22:04 iscsid
drwxr-xr-x 2 root root 0 Jan 25 22:04 issue
drwxr-xr-x 2 root root 0 Jan 25 22:04 k3s-service
drwxr-xr-x 4 root root 0 Jan 25 22:04 kubepods
-rw-r--r-- 1 root root 0 Jan 25 22:04 memory.pressure
drwxr-xr-x 2 root root 0 Jan 25 22:04 sshd
drwxr-xr-x 2 root root 0 Jan 25 22:04 syslog
drwxr-xr-x 2 root root 0 Jan 25 22:04 udev
k3os-11941 [~]$ kubectl get nodes
NAME         STATUS   ROLES                  AGE     VERSION
k3os-11941   Ready    control-plane,master   7m41s   v1.20.2+k3s-127b96e8
```

Comment (brandond) [reply pkg/daemons/agent/agent.go:187]: olljanat if you are confirming that this works with OpenRC in unified mode then I'm satisfied. We can open another issue to track hybrid mode with the cpu,pids controllers in v2.

Comment (AkihiroSuda) [reply pkg/daemons/agent/agent.go:187]: "hybrid" mode is almost meaningless in the container ecosystem, because a controller cannot be enabled for both v1 and v2 simultaneously.

Comment (brandond) [reply pkg/daemons/agent/agent.go:187]: Yeah hybrid mostly just means we should check v2 and fall back to v1. Right now we just assume they are available in v1 in hybrid mode.

Comment (olljanat) [reply pkg/daemons/agent/agent.go:187]: If the case is that without this one k3s fails to start if cgroup v2 is used then I can confirm that it works OpenRC in unified mode. Or is there something else what I should check?

**Comment by AkihiroSuda** [comment]
Would it be possible to get CI for this? https://github.com/k3s-io/k3s/issues/2845

GitHub Actions with Vagrant  can be used for small testing, though probably too heavy for the entire sonobuoy testing.

**Comment by phedders** [comment]
Would it be possible to expedite a new release to include #2844 ?
Many thanks!

**Comment by brandond** [comment]
We will probably just wait for the next upstream patch release: #2857

**Comment by sjkeerthi** [comment]
I know it's too late just want to get clarification if these features enabled will be supported on the latest k3s with the latest Kubernetes or will it be considered some other last three or four Kubernetes support?

Like for example will It be available on
1.19.x
1.20.x
1.21.x
1.22.x
