### PR TITLE
Disable helm CRD installation for disable-helm-controller

### LINKED ISSUE #8701: Helm CRDS are installed despite turning off helm-controller
What's the source for the helm CRDs, they are getting installed even when the helm controller is not enabled
```
 journalctl -u k3s | grep -i helm
Oct 19 18:51:02 ip-XXXX.us-west-2.compute.internal k3s[6713]: time="2023-10-19T18:51:02Z" level=info msg="Applying CRD helmcharts.helm.cattle.io"
Oct 19 18:51:02 ip-XXXX.us-west-2.compute.internal k3s[6713]: time="2023-10-19T18:51:02Z" level=info msg="Applying CRD helmchartconfigs.helm.cattle.io"
Oct 19 18:51:02 ip-XXXX.us-west-2.compute.internal k3s[6713]: I1019 18:51:02.106789    6713 handler.go:232] Adding GroupVersion helm.cattle.io v1 to ResourceManager
Oct 19 18:51:02 ip-XXXX.us-west-2.compute.internal k3s[6713]: I1019 18:51:02.107290    6713 handler.go:232] Adding GroupVersion helm.cattle.io v1 to ResourceManager
Oct 19 18:51:02 ip-XXXX.us-west-2.compute.internal k3s[6713]: I1019 18:51:02.109724    6713 handler.go:232] Adding GroupVersion helm.cattle.io v1 to ResourceManager
Oct 19 18:51:02 ip-XXXX.us-west-2.compute.internal k3s[6713]: I1019 18:51:02.112423    6713 handler.go:232] Adding GroupVersion helm.cattle.io v1 to ResourceManager
Oct 19 18:51:13 ip-XXXX.us-west-2.compute.internal k3s[6713]: time="2023-10-19T18:51:13Z" level=info msg="Imported docker.io/rancher/klipper-helm:v0.8.2-build20230815"
Oct 19 18:51:15 ip-XXXX.us-west-2.compute.internal k3s[6713]: I1019 18:51:15.329574    6713 resource_quota_monitor.go:210] "QuotaMonitor created object count evaluator" resource="helmchartconfigs.helm.cattle.io"
Oct 19 18:51:15 ip-XXXX.us-west-2.compute.internal k3s[6713]: I1019 18:51:15.329681    6713 resource_quota_monitor.go:210] "QuotaMonitor created object count evaluator" resource="helmcharts.helm.cattle.io"
Oct 19 18:56:00 ip-XXXX.us-west-2.compute.internal k3s[6713]: I1019 18:56:00.098836    6713 handler.go:232] Adding GroupVersion helm.cattle.io v1 to ResourceManager
Oct 19 18:56:00 ip-XXXX.us-west-2.compute.internal k3s[6713]: I1019 18:56:00.098869    6713 handler.go:232] Adding GroupVersion helm.cattle.io v1 to ResourceManager
```

**Environmental Info:**
K3s Version: 

k3s -v
k3s version v1.28.2+k3s1 (6330a5b4)
go version go1.20.8

Node(s) CPU architecture, OS, and Version: 

Linux ip-XXXX.us-west-2.compute.internal 5.14.0-375.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Oct 9 16:32:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

Single control-plane node.

**Describe the bug:**

Expected helm CRDs to be not installed when 

**Steps To Reproduce:**

- Installed K3s: 
Relevant config
```
protect-kernel-defaults: true
disable-cloud-controller: true
disable-helm-controller: true
disable-network-policy: true
disable:
  - traefik
  - servicelb
  - helm-controller
 ```

**Expected behavior:**
Helm CRDs to not install when disable-helm-controller

**Actual behavior:**

```
kubectl api-resources | grep helm
helmchartconfigs                               helm.cattle.io/v1                      true         HelmChartConfig
helmcharts                                     helm.cattle.io/v1                      true         HelmChart
```
**Additional context / logs:**

### PR DESCRIPTION
**Pull request by harsimranmaan**
The NewContext package requires config as input which would require all third-party callers to update when the new go module is published.

This change only affects the behaviour of installation of helm CRDs. Existing helm crds installed in a cluster would not be removed when disable-helm-controller flag is set on the server.

Addresses #8701

#### Proposed Changes ####
Disable helm CRD installation for disable-helm-controller

#### Types of Changes ####
Breaking Change (for sdk) not for k3s service

#### Linked Issues ####
* #8701 

#### User-Facing Change ####

```release-note

```

#### Further Comments ####

Closes #8701

### CODE REVIEW

File: pkg/cli/etcdsnapshot/etcd_snapshot.go [hunk 1]
```diff
@@ -86,7 +86,7 @@ func commandSetup(app *cli.Context, cfg *cmds.Server, config *server.Config) (*e
 		return nil, fmt.Errorf("etcd database not found in %s", config.ControlConfig.DataDir)
 	}
 
-	sc, err := server.NewContext(ctx, config.ControlConfig.Runtime.KubeConfigAdmin, false)
+	sc, err := server.NewContext(ctx, config, config.ControlConfig.Runtime.KubeConfigAdmin, false)
```
Comment (brandond) [inline pkg/cli/etcdsnapshot/etcd_snapshot.go:89]:
```suggestion
	sc, err := server.NewContext(ctx, config, false)
```

File: pkg/server/context.go [hunk 2]
```diff
@@ -38,7 +38,7 @@ func (c *Context) Start(ctx context.Context) error {
 	return start.All(ctx, 5, c.K3s, c.Helm, c.Apps, c.Auth, c.Batch, c.Core)
 }
 
-func NewContext(ctx context.Context, cfg string, forServer bool) (*Context, error) {
+func NewContext(ctx context.Context, serverConfig *Config, cfg string, forServer bool) (*Context, error) {
 	restConfig, err := clientcmd.BuildConfigFromFlags("", cfg)
```
Comment (brandond) [inline pkg/server/context.go:42]:
```suggestion
func NewContext(ctx context.Context, config *Config, forServer bool) (*Context, error) {
	var cfg string
	if forServer {
		cfg = config.ControlConfig.Runtime.KubeConfigSupervisor
	} else {
		cfg = config.ControlConfig.Runtime.KubeConfigAdmin
	}
	restConfig, err := clientcmd.BuildConfigFromFlags("", cfg)
```

File: pkg/server/context.go [hunk 3]
```diff
@@ -53,7 +53,7 @@ func NewContext(ctx context.Context, cfg string, forServer bool) (*Context, erro
 	var recorder record.EventRecorder
 	if forServer {
 		recorder = util.BuildControllerEventRecorder(k8s, version.Program+"-supervisor", metav1.NamespaceAll)
-		if err := crds(ctx, restConfig); err != nil {
+		if err := registerCrds(ctx, serverConfig, restConfig); err != nil {
```
Comment (brandond) [inline pkg/server/context.go:56]:
```suggestion
		if err := registerCrds(ctx, config, restConfig); err != nil {
```

File: pkg/server/context.go [hunk 4]
```diff
@@ -70,14 +70,21 @@ func NewContext(ctx context.Context, cfg string, forServer bool) (*Context, erro
 	}, nil
 }
 
-func crds(ctx context.Context, config *rest.Config) error {
-	factory, err := crd.NewFactoryFromClient(config)
+func registerCrds(ctx context.Context, serverConfig *Config, restConfig *rest.Config) error {
```
Comment (brandond) [inline pkg/server/context.go:73]:
```suggestion
func registerCrds(ctx context.Context, config *Config, restConfig *rest.Config) error {
```

File: pkg/server/context.go [hunk 5]
```diff
@@ -70,14 +70,21 @@ func NewContext(ctx context.Context, cfg string, forServer bool) (*Context, erro
...
-	types := append(helmcrd.List(), addoncrd.List()...)
-	factory.BatchCreateCRDs(ctx, types...)
+	factory.BatchCreateCRDs(ctx, crds(serverConfig)...)
 
 	return factory.BatchWait()
 }
+
+func crds(serverConfig *Config) []crd.CRD {
+	defaultCrds := addoncrd.List()
+	if serverConfig == nil || !serverConfig.ControlConfig.DisableHelmController {
```
Comment (brandond) [inline pkg/server/context.go:86]:
```suggestion
func crds(config *Config) []crd.CRD {
	defaultCrds := addoncrd.List()
	if serverConfig == nil || !config.ControlConfig.DisableHelmController {
```

File: pkg/server/server.go [hunk 6]
```diff
@@ -97,7 +97,7 @@ func startOnAPIServerReady(ctx context.Context, config *Config) {
 func runControllers(ctx context.Context, config *Config) error {
 	controlConfig := &config.ControlConfig
 
-	sc, err := NewContext(ctx, controlConfig.Runtime.KubeConfigSupervisor, true)
+	sc, err := NewContext(ctx, config, controlConfig.Runtime.KubeConfigSupervisor, true)
```
Comment (brandond) [inline pkg/server/server.go:100]:
```suggestion
	sc, err := NewContext(ctx, config, true)
```

**Review by brandond — CHANGES_REQUESTED** [review]
I don't like passing in both a struct, and a field on that struct. Just pass in the Config struct, and use the `forServer` flag to determine which config to use.

**Review by brandond — APPROVED** [review]

**Comment by brandond** [comment]
LGTM! We can squash when merging.

**Comment by harsimranmaan** [comment]
Hi @brandond, lemme know if this require any further work. Feel free to merge it

**Comment by brandond** [comment]
You're all set.We're in code freeze pending release of last week's patches. We will merge things again once the releases are out.

**Review by dereknola — APPROVED** [review]

**Comment by brandond** [comment]
arm and s390x are flaking; merging
